name: Python CI with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug: проверить Dockerfile
      - name: Show Dockerfile info
        run: |
          ls -la
          wc -c Dockerfile
          cat Dockerfile

      # Сборка Docker образа
      - name: Build Docker image
        run: docker build -t myapp -f Dockerfile .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Сборка Docker образа повторно, если нужен fresh build
      - name: Build Docker image again
        run: docker build -t myapp -f Dockerfile .

      # Запуск контейнера с тестами
      - name: Run tests inside Docker
        run: docker run --rm myapp